replicaCount: 3

image:
  repository: user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3002

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: user-service-secrets
        key: database-url