name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./applications/product-service
      - name: Run Tests
        run: npm test
        working-directory: ./applications/product-service
      - name: Build Docker Image
        run: docker build -t product-service .
        working-directory: ./applications/product-service
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'product-service'
          format: 'table'
          exit-code: '1'